services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - salon_net

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - salon_net

  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    networks:
      - salon_net

volumes:
  mongo_data:

networks:
  salon_net:
    driver: bridge
  